import Head from "next/head";
import dynamic from "next/dynamic";
import { CoralThemeProvider, GlobalCss } from "@krakentech/coral";

const Main = dynamic(() => import("@/components/Main"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://static.octopuscdn.com/fonts/Chromatophore/fonts.min.css"
        />
      </Head>

      <CoralThemeProvider>
        <GlobalCss />
        <Main />
      </CoralThemeProvider>
    </>
  );
}
